package dev.mathops.db.rawrecord;

import dev.mathops.core.EqualityTests;
import dev.mathops.core.builder.HtmlBuilder;
import dev.mathops.db.TermKey;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Objects;

/**
 * A raw "cusection" record.
 */
public final class RawCusection extends RawTermRecordBase implements Comparable<RawCusection> {

    /** A field name. */
    private static final String FLD_COURSE = "course";

    /** A field name. */
    private static final String FLD_SECT = "sect";

    /** A field name. */
    private static final String FLD_UNIT = "unit";

    /** A field name. */
    private static final String FLD_TIMEOUT = "timeout";

    /** A field name. */
    private static final String FLD_RE_MASTERY_SCORE = "re_mastery_score";

    /** A field name. */
    private static final String FLD_UE_MASTERY_SCORE = "ue_mastery_score";

    /** A field name. */
    private static final String FLD_HW_MASTERY_SCORE = "hw_mastery_score";

    /** A field name. */
    private static final String FLD_HW_MOVEON_SCORE = "hw_moveon_score";

    /** A field name. */
    private static final String FLD_NBR_ATMPTS_ALLOW = "nbr_atmpts_allow";

    /** A field name. */
    private static final String FLD_ATMPTS_PER_REVIEW = "atmpts_per_review";

    /** A field name. */
    private static final String FLD_FIRST_TEST_DT = "first_test_dt";

    /** A field name. */
    private static final String FLD_LAST_TEST_DT = "last_test_dt";

    /** A field name. */
    private static final String FLD_BEGIN_TEST_PERIOD = "begin_test_period";

    /** A field name. */
    private static final String FLD_END_TEST_PERIOD = "end_test_period";

    /** A field name. */
    private static final String FLD_COUPON_COST = "coupon_cost";

    /** A field name. */
    private static final String FLD_LAST_COUPON_DT = "last_coupon_dt";

    /** A field name. */
    private static final String FLD_SHOW_TEST_WINDOW = "show_test_window";

    /** A field name. */
    private static final String FLD_UNPROCTORED_EXAM = "unproctored_exam";

    /** A field name. */
    private static final String FLD_RE_POINTS_ONTIME = "re_points_ontime";

    /** The 'course' field value. */
    public String course;

    /** The 'sect' field value. */
    public String sect;

    /** The 'unit' field value. */
    public Integer unit;

    /** The 'timeout' field value. */
    public Integer timeout;

    /** The 're_mastery_score' field value. */
    public Integer reMasteryScore;

    /** The 'ue_mastery_score' field value. */
    public Integer ueMasteryScore;

    /** The 'hw_mastery_score' field value. */
    public Integer hwMasteryScore;

    /** The 'hw_moveon_score' field value. */
    public Integer hwMoveonScore;

    /** The 'nbr_atmpts_allow' field value. */
    public Integer nbrAtmptsAllow;

    /** The 'atmpts_per_review' field value. */
    public Integer atmptsPerReview;

    /** The 'first_test_dt' field value. */
    public LocalDate firstTestDt;

    /** The 'last_test_dt' field value. */
    public LocalDate lastTestDt;

    /** The 'begin_test_period' field value. */
    public Integer beginTestPeriod;

    /** The 'end_test_period' field value. */
    public Integer endTestPeriod;

    /** The 'coupon_cost' field value. */
    public Integer couponCost;

    /** The 'last_coupon_dt' field value. */
    public LocalDate lastCouponDt;

    /** The 'show_test_window' field value. */
    public String showTestWindow;

    /** The 'unproctored_exam' field value. */
    public String unproctoredExam;

    /** The 'rePointsOntime' field value. */
    public Integer rePointsOntime;

    /**
     * Constructs a new {@code RawCusection}.
     */
    private RawCusection() {

        super();
    }

    /**
     * Constructs a new {@code RawCusection} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static RawCusection parse(final String toParse) {

        final RawCusection result = new RawCusection();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown if a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_TERM.equals(name)) {
            this.termKey = TermKey.parseLongString(value);
        } else if (FLD_COURSE.equals(name)) {
            this.course = value;
        } else if (FLD_SECT.equals(name)) {
            this.sect = value;
        } else if (FLD_UNIT.equals(name)) {
            this.unit = Integer.valueOf(value);
        } else if (FLD_TIMEOUT.equals(name)) {
            this.timeout = Integer.valueOf(value);
        } else if (FLD_RE_MASTERY_SCORE.equals(name)) {
            this.reMasteryScore = Integer.valueOf(value);
        } else if (FLD_UE_MASTERY_SCORE.equals(name)) {
            this.ueMasteryScore = Integer.valueOf(value);
        } else if (FLD_HW_MASTERY_SCORE.equals(name)) {
            this.hwMasteryScore = Integer.valueOf(value);
        } else if (FLD_HW_MOVEON_SCORE.equals(name)) {
            this.hwMoveonScore = Integer.valueOf(value);
        } else if (FLD_NBR_ATMPTS_ALLOW.equals(name)) {
            this.nbrAtmptsAllow = Integer.valueOf(value);
        } else if (FLD_ATMPTS_PER_REVIEW.equals(name)) {
            this.atmptsPerReview = Integer.valueOf(value);
        } else if (FLD_FIRST_TEST_DT.equals(name)) {
            this.firstTestDt = LocalDate.parse(value);
        } else if (FLD_LAST_TEST_DT.equals(name)) {
            this.lastTestDt = LocalDate.parse(value);
        } else if (FLD_BEGIN_TEST_PERIOD.equals(name)) {
            this.beginTestPeriod = Integer.valueOf(value);
        } else if (FLD_END_TEST_PERIOD.equals(name)) {
            this.endTestPeriod = Integer.valueOf(value);
        } else if (FLD_COUPON_COST.equals(name)) {
            this.couponCost = Integer.valueOf(value);
        } else if (FLD_LAST_COUPON_DT.equals(name)) {
            this.lastCouponDt = LocalDate.parse(value);
        } else if (FLD_SHOW_TEST_WINDOW.equals(name)) {
            this.showTestWindow = value;
        } else if (FLD_UNPROCTORED_EXAM.equals(name)) {
            this.unproctoredExam = value;
        } else if (FLD_RE_POINTS_ONTIME.equals(name)) {
            this.rePointsOntime = Integer.valueOf(value);
        }
    }

    /**
     * Constructs a new {@code RawCusection}.
     *
     * @param theTermKey         the term key
     * @param theCourse          the course
     * @param theSect            the section
     * @param theUnit            the unit
     * @param theTimeout         the timeout
     * @param theReMasteryStore  the review exam mastery score
     * @param theUeMasteryScore  the unit exam mastery score
     * @param theHwMasteryScore  the homework mastery score
     * @param theHwMoveonScore   the homework move-on score
     * @param theNbrAtmptsAllow  the total number of unit/final exam attempts allowed
     * @param theAtmptsPerReview the number of unit exam attempts per review exam
     * @param theFirstTestDt     the first date the unit exam can be taken
     * @param theLastTestDt      the last date the unit exam can be taken
     * @param theBeginTestPeriod the beginning of the test period
     * @param theEndTestPeriod   the end of the test period
     * @param theCouponCost      the cost in coupons to take the unit exam outside the testing window
     * @param theLastCouponDt    the last date unit exam can be taken with coupons
     * @param theShowTestWindow  "Y" to show the testing window
     * @param theUnproctoredExam the "Y" to allow the unit exam to be taken unproctored
     * @param theRePointsOntime  the number of points awarded for completing the review exam on time
     */
    public RawCusection(final TermKey theTermKey, final String theCourse, final String theSect,
                        final Integer theUnit, final Integer theTimeout, final Integer theReMasteryStore,
                        final Integer theUeMasteryScore, final Integer theHwMasteryScore,
                        final Integer theHwMoveonScore, final Integer theNbrAtmptsAllow,
                        final Integer theAtmptsPerReview, final LocalDate theFirstTestDt,
                        final LocalDate theLastTestDt, final Integer theBeginTestPeriod,
                        final Integer theEndTestPeriod, final Integer theCouponCost,
                        final LocalDate theLastCouponDt, final String theShowTestWindow,
                        final String theUnproctoredExam, final Integer theRePointsOntime) {

        super(theTermKey);

        this.course = theCourse;
        this.sect = theSect;
        this.unit = theUnit;
        this.timeout = theTimeout;
        this.reMasteryScore = theReMasteryStore;
        this.ueMasteryScore = theUeMasteryScore;
        this.hwMasteryScore = theHwMasteryScore;
        this.hwMoveonScore = theHwMoveonScore;
        this.nbrAtmptsAllow = theNbrAtmptsAllow;
        this.atmptsPerReview = theAtmptsPerReview;
        this.firstTestDt = theFirstTestDt;
        this.lastTestDt = theLastTestDt;
        this.beginTestPeriod = theBeginTestPeriod;
        this.endTestPeriod = theEndTestPeriod;
        this.couponCost = theCouponCost;
        this.lastCouponDt = theLastCouponDt;
        this.showTestWindow = theShowTestWindow;
        this.unproctoredExam = theUnproctoredExam;
        this.rePointsOntime = theRePointsOntime;
    }

    /**
     * Extracts a "cusection" record from a result set.
     *
     * @param rs the result set from which to retrieve the record
     * @return the record
     * @throws SQLException if there is an error accessing the database
     */
    public static RawCusection fromResultSet(final ResultSet rs) throws SQLException {

        final RawCusection result = new RawCusection();

        result.course = getStringField(rs, FLD_COURSE);
        result.sect = getStringField(rs, FLD_SECT);
        result.unit = getIntegerField(rs, FLD_UNIT);
        result.termKey = getTermAndYear(rs, FLD_TERM, FLD_TERM_YR);
        result.timeout = getIntegerField(rs, FLD_TIMEOUT);
        result.reMasteryScore = getIntegerField(rs, FLD_RE_MASTERY_SCORE);
        result.ueMasteryScore = getIntegerField(rs, FLD_UE_MASTERY_SCORE);
        result.hwMasteryScore = getIntegerField(rs, FLD_HW_MASTERY_SCORE);
        result.hwMoveonScore = getIntegerField(rs, FLD_HW_MOVEON_SCORE);
        result.nbrAtmptsAllow = getIntegerField(rs, FLD_NBR_ATMPTS_ALLOW);
        result.atmptsPerReview = getIntegerField(rs, FLD_ATMPTS_PER_REVIEW);
        result.firstTestDt = getDateField(rs, FLD_FIRST_TEST_DT);
        result.lastTestDt = getDateField(rs, FLD_LAST_TEST_DT);
        result.beginTestPeriod = getIntegerField(rs, FLD_BEGIN_TEST_PERIOD);
        result.endTestPeriod = getIntegerField(rs, FLD_END_TEST_PERIOD);
        result.couponCost = getIntegerField(rs, FLD_COUPON_COST);
        result.lastCouponDt = getDateField(rs, FLD_LAST_COUPON_DT);
        result.showTestWindow = getStringField(rs, FLD_SHOW_TEST_WINDOW);
        result.unproctoredExam = getStringField(rs, FLD_UNPROCTORED_EXAM);
        result.rePointsOntime = getIntegerField(rs, FLD_RE_POINTS_ONTIME);

        return result;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final RawCusection o) {

        int result = this.termKey.compareTo(o.termKey);

        if (result == 0) {
            result = this.course.compareTo(o.course);
            if (result == 0) {
                result = this.sect.compareTo(o.sect);
                if (result == 0) {
                    result = this.unit.compareTo(o.unit);
                }
            }
        }

        return result;
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_TERM, this.termKey);
        htm.add(DIVIDER);
        appendField(htm, FLD_COURSE, this.course);
        htm.add(DIVIDER);
        appendField(htm, FLD_SECT, this.sect);
        htm.add(DIVIDER);
        appendField(htm, FLD_UNIT, this.unit);
        htm.add(DIVIDER);
        appendField(htm, FLD_TIMEOUT, this.timeout);
        htm.add(DIVIDER);
        appendField(htm, FLD_RE_MASTERY_SCORE, this.reMasteryScore);
        htm.add(DIVIDER);
        appendField(htm, FLD_UE_MASTERY_SCORE, this.ueMasteryScore);
        htm.add(DIVIDER);
        appendField(htm, FLD_HW_MASTERY_SCORE, this.hwMasteryScore);
        htm.add(DIVIDER);
        appendField(htm, FLD_HW_MOVEON_SCORE, this.hwMoveonScore);
        htm.add(DIVIDER);
        appendField(htm, FLD_NBR_ATMPTS_ALLOW, this.nbrAtmptsAllow);
        htm.add(DIVIDER);
        appendField(htm, FLD_ATMPTS_PER_REVIEW, this.atmptsPerReview);
        htm.add(DIVIDER);
        appendField(htm, FLD_FIRST_TEST_DT, this.firstTestDt);
        htm.add(DIVIDER);
        appendField(htm, FLD_LAST_TEST_DT, this.lastTestDt);
        htm.add(DIVIDER);
        appendField(htm, FLD_BEGIN_TEST_PERIOD, this.beginTestPeriod);
        htm.add(DIVIDER);
        appendField(htm, FLD_END_TEST_PERIOD, this.endTestPeriod);
        htm.add(DIVIDER);
        appendField(htm, FLD_COUPON_COST, this.couponCost);
        htm.add(DIVIDER);
        appendField(htm, FLD_LAST_COUPON_DT, this.lastCouponDt);
        htm.add(DIVIDER);
        appendField(htm, FLD_SHOW_TEST_WINDOW, this.showTestWindow);
        htm.add(DIVIDER);
        appendField(htm, FLD_UNPROCTORED_EXAM, this.unproctoredExam);
        htm.add(DIVIDER);
        appendField(htm, FLD_RE_POINTS_ONTIME, this.rePointsOntime);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return EqualityTests.objectHashCode(this.termKey)
                + EqualityTests.objectHashCode(this.course)
                + EqualityTests.objectHashCode(this.sect)
                + EqualityTests.objectHashCode(this.unit)
                + EqualityTests.objectHashCode(this.timeout)
                + EqualityTests.objectHashCode(this.reMasteryScore)
                + EqualityTests.objectHashCode(this.ueMasteryScore)
                + EqualityTests.objectHashCode(this.hwMasteryScore)
                + EqualityTests.objectHashCode(this.hwMoveonScore)
                + EqualityTests.objectHashCode(this.nbrAtmptsAllow)
                + EqualityTests.objectHashCode(this.atmptsPerReview)
                + EqualityTests.objectHashCode(this.firstTestDt)
                + EqualityTests.objectHashCode(this.lastTestDt)
                + EqualityTests.objectHashCode(this.beginTestPeriod)
                + EqualityTests.objectHashCode(this.endTestPeriod)
                + EqualityTests.objectHashCode(this.couponCost)
                + EqualityTests.objectHashCode(this.lastCouponDt)
                + EqualityTests.objectHashCode(this.showTestWindow)
                + EqualityTests.objectHashCode(this.unproctoredExam)
                + EqualityTests.objectHashCode(this.rePointsOntime);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final RawCusection rec) {
            equal = Objects.equals(this.termKey, rec.termKey)
                    && Objects.equals(this.course, rec.course)
                    && Objects.equals(this.sect, rec.sect)
                    && Objects.equals(this.unit, rec.unit)
                    && Objects.equals(this.timeout, rec.timeout)
                    && Objects.equals(this.reMasteryScore, rec.reMasteryScore)
                    && Objects.equals(this.ueMasteryScore, rec.ueMasteryScore)
                    && Objects.equals(this.hwMasteryScore, rec.hwMasteryScore)
                    && Objects.equals(this.hwMoveonScore, rec.hwMoveonScore)
                    && Objects.equals(this.nbrAtmptsAllow, rec.nbrAtmptsAllow)
                    && Objects.equals(this.atmptsPerReview, rec.atmptsPerReview)
                    && Objects.equals(this.firstTestDt, rec.firstTestDt)
                    && Objects.equals(this.lastTestDt, rec.lastTestDt)
                    && Objects.equals(this.beginTestPeriod, rec.beginTestPeriod)
                    && Objects.equals(this.endTestPeriod, rec.endTestPeriod)
                    && Objects.equals(this.couponCost, rec.couponCost)
                    && Objects.equals(this.lastCouponDt, rec.lastCouponDt)
                    && Objects.equals(this.showTestWindow, rec.showTestWindow)
                    && Objects.equals(this.unproctoredExam, rec.unproctoredExam)
                    && Objects.equals(this.rePointsOntime, rec.rePointsOntime);
        } else {
            equal = false;
        }

        return equal;
    }
}
