package dev.mathops.db.rawrecord;

import dev.mathops.core.EqualityTests;
import dev.mathops.core.builder.HtmlBuilder;
import dev.mathops.db.TermKey;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Objects;

/**
 * A raw "dont_submit" record.
 */
public final class RawDontSubmit extends RawTermRecordBase implements Comparable<RawDontSubmit> {

    /** A field name. */
    private static final String FLD_COURSE = "course";

    /** A field name. */
    private static final String FLD_SECT = "sect";

    /** The 'course' field value. */
    public String course;

    /** The 'sect' field value. */
    public String sect;

    /**
     * Constructs a new {@code RawDontSubmit}.
     */
    private RawDontSubmit() {

        super();
    }

    /**
     * Constructs a new {@code RawDontSubmit} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static RawDontSubmit parse(final String toParse) {

        final RawDontSubmit result = new RawDontSubmit();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown if a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_TERM.equals(name)) {
            this.termKey = TermKey.parseLongString(value);
        } else if (FLD_COURSE.equals(name)) {
            this.course = value;
        } else if (FLD_SECT.equals(name)) {
            this.sect = value;
        }
    }

    /**
     * Constructs a new {@code RawDontSubmit}.
     *
     * @param theTermKey the term key
     * @param theCourse  the course
     * @param theSect    the section number
     */
    public RawDontSubmit(final TermKey theTermKey, final String theCourse, final String theSect) {

        super(theTermKey);

        this.course = theCourse;
        this.sect = theSect;
    }

    /**
     * Extracts an "dont_submit" record from a result set.
     *
     * @param rs the result set from which to retrieve the record
     * @return the record
     * @throws SQLException if there is an error accessing the database
     */
    public static RawDontSubmit fromResultSet(final ResultSet rs) throws SQLException {

        final RawDontSubmit result = new RawDontSubmit();

        result.course = getStringField(rs, FLD_COURSE);
        result.sect = getStringField(rs, FLD_SECT);
        result.termKey = getTermAndYear(rs, FLD_TERM, FLD_TERM_YR);

        return result;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final RawDontSubmit o) {

        int result = compareAllowingNull(this.course, o.course);

        if (result == 0) {
            result = compareAllowingNull(this.sect, o.sect);
        }

        return result;
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_TERM, this.termKey);
        htm.add(DIVIDER);
        appendField(htm, FLD_COURSE, this.course);
        htm.add(DIVIDER);
        appendField(htm, FLD_SECT, this.sect);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return EqualityTests.objectHashCode(this.termKey)
                + EqualityTests.objectHashCode(this.course)
                + EqualityTests.objectHashCode(this.sect);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final RawDontSubmit rec) {
            equal = Objects.equals(this.termKey, rec.termKey)
                    && Objects.equals(this.course, rec.course)
                    && Objects.equals(this.sect, rec.sect);
        } else {
            equal = false;
        }

        return equal;
    }
}
