package dev.mathops.db.rawrecord;

import dev.mathops.core.EqualityTests;
import dev.mathops.core.builder.HtmlBuilder;
import dev.mathops.db.rec.RecBase;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Objects;

/**
 * A raw "mpe_credit" record.
 */
public final class RawMpeCredit extends RecBase implements Comparable<RawMpeCredit> {

    /** A field name. */
    private static final String FLD_STU_ID = "stu_id";

    /** A field name. */
    private static final String FLD_COURSE = "course";

    /** A field name. */
    private static final String FLD_EXAM_PLACED = "exam_placed";

    /** A field name. */
    private static final String FLD_EXAM_DT = "exam_dt";

    /** A field name. */
    private static final String FLD_DT_CR_REFUSED = "dt_cr_refused";

    /** A field name. */
    private static final String FLD_SERIAL_NBR = "serial_nbr";

    /** A field name. */
    private static final String FLD_VERSION = "version";

    /** A field name. */
    private static final String FLD_EXAM_SOURCE = "exam_source";

    /** The 'stu_id' field value. */
    public String stuId;

    /** The 'course' field value. */
    public String course;

    /** The 'exam_placed' field value. */
    public String examPlaced;

    /** The 'exam_dt' field value. */
    public LocalDate examDt;

    /** The 'dt_cr_refused' field value. */
    public LocalDate dtCrRefused;

    /** The 'serial_nbr' field value. */
    public Long serialNbr;

    /** The 'version' field value. */
    public String version;

    /** The 'exam_source' field value. */
    public String examSource;

    /**
     * Constructs a new {@code RawMpeCredit}.
     */
    private RawMpeCredit() {

        super();
    }

    /**
     * Constructs a new {@code RawMpeCredit} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static RawMpeCredit parse(final String toParse) {

        final RawMpeCredit result = new RawMpeCredit();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown if a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_STU_ID.equals(name)) {
            this.stuId = value;
        } else if (FLD_COURSE.equals(name)) {
            this.course = value;
        } else if (FLD_EXAM_PLACED.equals(name)) {
            this.examPlaced = value;
        } else if (FLD_EXAM_DT.equals(name)) {
            this.examDt = LocalDate.parse(value);
        } else if (FLD_DT_CR_REFUSED.equals(name)) {
            this.dtCrRefused = LocalDate.parse(value);
        } else if (FLD_SERIAL_NBR.equals(name)) {
            this.serialNbr = Long.valueOf(value);
        } else if (FLD_VERSION.equals(name)) {
            this.version = value;
        } else if (FLD_EXAM_SOURCE.equals(name)) {
            this.examSource = value;
        }
    }

    /**
     * Constructs a new {@code RawMpeCredit}.
     *
     * @param theStuId       the student ID
     * @param theCourse      the course
     * @param theExamPlaced  the exam placed flag
     * @param theExamDt      the exam date
     * @param theDtCrRefused date credit was refused
     * @param theSerialNbr   the serial number
     * @param theVersion     the version
     * @param theExamSource  the exam source
     */
    public RawMpeCredit(final String theStuId, final String theCourse, final String theExamPlaced,
                        final LocalDate theExamDt, final LocalDate theDtCrRefused, final Long theSerialNbr,
                        final String theVersion, final String theExamSource) {

        super();

        this.stuId = theStuId;
        this.course = theCourse;
        this.examPlaced = theExamPlaced;
        this.examDt = theExamDt;
        this.dtCrRefused = theDtCrRefused;
        this.serialNbr = theSerialNbr;
        this.version = theVersion;
        this.examSource = theExamSource;
    }

    /**
     * Extracts an "mpe_credit" record from a result set.
     *
     * @param rs the result set from which to retrieve the record
     * @return the record
     * @throws SQLException if there is an error accessing the database
     */
    public static RawMpeCredit fromResultSet(final ResultSet rs) throws SQLException {

        final RawMpeCredit result = new RawMpeCredit();

        result.stuId = getStringField(rs, FLD_STU_ID);
        result.course = getStringField(rs, FLD_COURSE);
        result.examPlaced = getStringField(rs, FLD_EXAM_PLACED);
        result.examDt = getDateField(rs, FLD_EXAM_DT);
        result.dtCrRefused = getDateField(rs, FLD_DT_CR_REFUSED);
        result.serialNbr = getLongField(rs, FLD_SERIAL_NBR);
        result.version = getStringField(rs, FLD_VERSION);
        result.examSource = getStringField(rs, FLD_EXAM_SOURCE);

        return result;
    }

    /**
     * Generates the string representation of the object.
     *
     * @return the string representation
     */
    @Override
    public String toString() {

        return this.course + " (" + this.examPlaced + ")";
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final RawMpeCredit o) {

        int result = compareAllowingNull(this.stuId, o.stuId);

        if (result == 0) {
            result = compareAllowingNull(this.course, o.course);
            if (result == 0) {
                result = compareAllowingNull(this.examDt, o.examDt);
            }
        }

        return result;
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_STU_ID, this.stuId);
        htm.add(DIVIDER);
        appendField(htm, FLD_COURSE, this.course);
        htm.add(DIVIDER);
        appendField(htm, FLD_EXAM_PLACED, this.examPlaced);
        htm.add(DIVIDER);
        appendField(htm, FLD_EXAM_DT, this.examDt);
        htm.add(DIVIDER);
        appendField(htm, FLD_DT_CR_REFUSED, this.dtCrRefused);
        htm.add(DIVIDER);
        appendField(htm, FLD_SERIAL_NBR, this.serialNbr);
        htm.add(DIVIDER);
        appendField(htm, FLD_VERSION, this.version);
        htm.add(DIVIDER);
        appendField(htm, FLD_EXAM_SOURCE, this.examSource);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return EqualityTests.objectHashCode(this.stuId)
                + EqualityTests.objectHashCode(this.course)
                + EqualityTests.objectHashCode(this.examPlaced)
                + EqualityTests.objectHashCode(this.examDt)
                + EqualityTests.objectHashCode(this.dtCrRefused)
                + EqualityTests.objectHashCode(this.serialNbr)
                + EqualityTests.objectHashCode(this.version)
                + EqualityTests.objectHashCode(this.examSource);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final RawMpeCredit rec) {
            equal = Objects.equals(this.stuId, rec.stuId)
                    && Objects.equals(this.course, rec.course)
                    && Objects.equals(this.examPlaced, rec.examPlaced)
                    && Objects.equals(this.examDt, rec.examDt)
                    && Objects.equals(this.dtCrRefused, rec.dtCrRefused)
                    && Objects.equals(this.serialNbr, rec.serialNbr)
                    && Objects.equals(this.version, rec.version)
                    && Objects.equals(this.examSource, rec.examSource);
        } else {
            equal = false;
        }

        return equal;
    }
}
