package dev.mathops.db.rawrecord;

import dev.mathops.core.EqualityTests;
import dev.mathops.core.builder.HtmlBuilder;
import dev.mathops.db.rec.RecBase;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Objects;

/**
 * A raw "stcuobjective" record.
 */
public final class RawStcuobjective extends RecBase implements Comparable<RawStcuobjective> {

    /** A field name. */
    private static final String FLD_STU_ID = "stu_id";

    /** A field name. */
    private static final String FLD_COURSE = "course";

    /** A field name. */
    private static final String FLD_UNIT = "unit";

    /** A field name. */
    private static final String FLD_OBJECTIVE = "objective";

    /** A field name. */
    private static final String FLD_LECTURE_VIEWED_DT = "lecture_viewed_dt";

    /** A field name. */
    private static final String FLD_SEED = "seed";

    /** A field name. */
    private static final String FLD_LAST_COMPONENT_FINISHED = "last_component_finished";

    /** The 'stu_id' field value. */
    public String stuId;

    /** The 'course' field value. */
    public String course;

    /** The 'unit' field value. */
    public Integer unit;

    /** The 'objective' field value. */
    public Integer objective;

    /** The 'lecture_viewed_dt' field value. */
    public LocalDate lectureViewedDt;

    /** The 'seed' field value. */
    public Integer seed;

    /** The 'last_component_finished' field value. */
    public Integer lastComponentFinished;

    /**
     * Constructs a new {@code RawStcuobjective}.
     */
    private RawStcuobjective() {

        super();
    }

    /**
     * Constructs a new {@code RawStcuobjective} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static RawStcuobjective parse(final String toParse) {

        final RawStcuobjective result = new RawStcuobjective();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * If a field name is recognized, however, and the value provided cannot be interpreted, an
     * {@code IllegalArgumentException} is thrown. Such an exception is also thrown if the field name or value string is
     * {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_STU_ID.equals(name)) {
            this.stuId = value;
        } else if (FLD_COURSE.equals(name)) {
            this.course = value;
        } else if (FLD_UNIT.equals(name)) {
            this.unit = Integer.valueOf(value);
        } else if (FLD_OBJECTIVE.equals(name)) {
            this.objective = Integer.valueOf(value);
        } else if (FLD_LECTURE_VIEWED_DT.equals(name)) {
            this.lectureViewedDt = LocalDate.parse(value);
        } else if (FLD_SEED.equals(name)) {
            this.seed = Integer.valueOf(value);
        } else if (FLD_LAST_COMPONENT_FINISHED.equals(name)) {
            this.lastComponentFinished = Integer.valueOf(value);
        }
    }

    /**
     * Constructs a new {@code RawStcuobjective}.
     *
     * @param theStuId                 The 'stu_id' field value
     * @param theCourse                the 'course' field value
     * @param theUnit                  the 'unit' field value
     * @param theObjective             the 'objective' field value
     * @param theLectureViewedDt       the 'lecture_viewed_dt' field value
     * @param theSeed                  the 'seed' field value
     * @param theLastComponentFinished the 'last_component_finished' field value
     */
    public RawStcuobjective(final String theStuId, final String theCourse, final Integer theUnit,
                            final Integer theObjective, final LocalDate theLectureViewedDt, final Integer theSeed,
                            final Integer theLastComponentFinished) {

        super();

        this.stuId = theStuId;
        this.course = theCourse;
        this.unit = theUnit;
        this.objective = theObjective;
        this.lectureViewedDt = theLectureViewedDt;
        this.seed = theSeed;
        this.lastComponentFinished = theLastComponentFinished;
    }

    /**
     * Extracts an "stcuobjective" record from a result set.
     *
     * @param rs the result set from which to retrieve the record
     * @return the record
     * @throws SQLException if there is an error accessing the database
     */
    public static RawStcuobjective fromResultSet(final ResultSet rs) throws SQLException {

        final RawStcuobjective result = new RawStcuobjective();

        result.stuId = getStringField(rs, FLD_STU_ID);
        result.course = getStringField(rs, FLD_COURSE);
        result.unit = getIntegerField(rs, FLD_UNIT);
        result.objective = getIntegerField(rs, FLD_OBJECTIVE);
        result.lectureViewedDt = getDateField(rs, FLD_LECTURE_VIEWED_DT);
        result.seed = getIntegerField(rs, FLD_SEED);
        result.lastComponentFinished = getIntegerField(rs, FLD_LAST_COMPONENT_FINISHED);

        return result;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final RawStcuobjective o) {

        int result = compareAllowingNull(this.stuId, o.stuId);

        if (result == 0) {
            result = compareAllowingNull(this.course, o.course);

            if (result == 0) {
                result = compareAllowingNull(this.unit, o.unit);

                if (result == 0) {
                    result = compareAllowingNull(this.objective, o.objective);
                }
            }
        }

        return result;
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_STU_ID, this.stuId);
        htm.add(DIVIDER);
        appendField(htm, FLD_COURSE, this.course);
        htm.add(DIVIDER);
        appendField(htm, FLD_UNIT, this.unit);
        htm.add(DIVIDER);
        appendField(htm, FLD_OBJECTIVE, this.objective);
        htm.add(DIVIDER);
        appendField(htm, FLD_LECTURE_VIEWED_DT, this.lectureViewedDt);
        htm.add(DIVIDER);
        appendField(htm, FLD_SEED, this.seed);
        htm.add(DIVIDER);
        appendField(htm, FLD_LAST_COMPONENT_FINISHED, this.lastComponentFinished);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return EqualityTests.objectHashCode(this.stuId)
                + EqualityTests.objectHashCode(this.course)
                + EqualityTests.objectHashCode(this.unit)
                + EqualityTests.objectHashCode(this.objective)
                + EqualityTests.objectHashCode(this.lectureViewedDt)
                + EqualityTests.objectHashCode(this.seed)
                + EqualityTests.objectHashCode(this.lastComponentFinished);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final RawStcuobjective rec) {
            equal = Objects.equals(this.stuId, rec.stuId)
                    && Objects.equals(this.course, rec.course)
                    && Objects.equals(this.unit, rec.unit)
                    && Objects.equals(this.objective, rec.objective)
                    && Objects.equals(this.lectureViewedDt, rec.lectureViewedDt)
                    && Objects.equals(this.seed, rec.seed)
                    && Objects.equals(this.lastComponentFinished, rec.lastComponentFinished);
        } else {
            equal = false;
        }

        return equal;
    }
}
