package dev.mathops.db.rawrecord;

import dev.mathops.core.EqualityTests;
import dev.mathops.core.builder.HtmlBuilder;
import dev.mathops.db.rec.RecBase;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * A raw "stvisit" record.
 */
public final class RawStvisit extends RecBase implements Comparable<RawStvisit> {

    /** A field name. */
    private static final String FLD_STU_ID = "stu_id";

    /** A field name. */
    private static final String FLD_WHEN_STARTED = "when_started";

    /** A field name. */
    private static final String FLD_WHEN_ENDED = "when_ended";

    /** A field name. */
    private static final String FLD_LOCATION = "location";

    /** A field name. */
    private static final String FLD_SEAT = "seat";

    /** The 'stu_id' field value. */
    public String stuId;

    /** The 'when_started' field value. */
    public LocalDateTime whenStarted;

    /** The 'when_ended' field value. */
    public LocalDateTime whenEnded;

    /** The 'location' field value. */
    public String location;

    /** The 'seat' field value. */
    public String seat;

    /**
     * Constructs a new {@code RawStvisit}.
     */
    private RawStvisit() {

        super();
    }

    /**
     * Constructs a new {@code RawStvisit} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static RawStvisit parse(final String toParse) {

        final RawStvisit result = new RawStvisit();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown if a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_STU_ID.equals(name)) {
            this.stuId = value;
        } else if (FLD_WHEN_STARTED.equals(name)) {
            this.whenStarted = LocalDateTime.parse(value);
        } else if (FLD_WHEN_ENDED.equals(name)) {
            this.whenEnded = LocalDateTime.parse(value);
        } else if (FLD_LOCATION.equals(name)) {
            this.location = value;
        } else if (FLD_SEAT.equals(name)) {
            this.seat = value;
        }
    }

    /**
     * Constructs a new {@code RawStvisit}.
     *
     * @param theStuId       the student ID
     * @param theWhenStarted the date/time the visit started
     * @param theWhenEnded   the date/time the visit ended
     * @param theLocation    the pace track
     * @param theSeat        the assigned cohort
     */
    public RawStvisit(final String theStuId, final LocalDateTime theWhenStarted,
                      final LocalDateTime theWhenEnded, final String theLocation, final String theSeat) {

        super();

        this.stuId = theStuId;
        this.whenStarted = theWhenStarted;
        this.whenEnded = theWhenEnded;
        this.location = theLocation;
        this.seat = theSeat;
    }

    /**
     * Extracts a "stvisit" record from a result set.
     *
     * @param rs the result set from which to retrieve the record
     * @return the record
     * @throws SQLException if there is an error accessing the database
     */
    public static RawStvisit fromResultSet(final ResultSet rs) throws SQLException {

        final RawStvisit result = new RawStvisit();

        result.stuId = getStringField(rs, FLD_STU_ID);
        result.whenStarted = getDateTimeField(rs, FLD_WHEN_STARTED);
        result.whenEnded = getDateTimeField(rs, FLD_WHEN_ENDED);
        result.location = getStringField(rs, FLD_LOCATION);
        result.seat = getStringField(rs, FLD_SEAT);

        return result;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final RawStvisit o) {

        int result = this.stuId.compareTo(o.stuId);

        if (result == 0) {
            result = this.whenStarted.compareTo(o.whenStarted);
        }

        return result;
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_STU_ID, this.stuId);
        htm.add(DIVIDER);
        appendField(htm, FLD_WHEN_STARTED, this.whenStarted);
        htm.add(DIVIDER);
        appendField(htm, FLD_WHEN_ENDED, this.whenEnded);
        htm.add(DIVIDER);
        appendField(htm, FLD_LOCATION, this.location);
        htm.add(DIVIDER);
        appendField(htm, FLD_SEAT, this.seat);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return EqualityTests.objectHashCode(this.stuId)
                + EqualityTests.objectHashCode(this.whenStarted)
                + EqualityTests.objectHashCode(this.whenEnded)
                + EqualityTests.objectHashCode(this.location)
                + EqualityTests.objectHashCode(this.seat);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final RawStvisit rec) {
            equal = Objects.equals(this.stuId, rec.stuId)
                    && Objects.equals(this.whenStarted, rec.whenStarted)
                    && Objects.equals(this.whenEnded, rec.whenEnded)
                    && Objects.equals(this.location, rec.location)
                    && Objects.equals(this.seat, rec.seat);
        } else {
            equal = false;
        }

        return equal;
    }
}
