package dev.mathops.db.old.rec;

import dev.mathops.commons.CoreConstants;
import dev.mathops.commons.builder.HtmlBuilder;
import dev.mathops.db.enums.EGradeMode;
import dev.mathops.db.enums.EOfferingTermName;
import dev.mathops.db.enums.ETermName;
import dev.mathops.db.type.CatalogCourseNumber;

import java.util.EnumSet;
import java.util.Locale;
import java.util.Objects;

/**
 * A "catalog course" record.
 */
public final class CatalogCourseRec extends RecBase implements Comparable<CatalogCourseRec> {

    /** A possible component in the "allow" bit flag field. */
    public static final int ALLOW_FRESHMAN = 0x0001;

    /** A possible component in the "allow" bit flag field. */
    public static final int ALLOW_SOPHOMORE = 0x0002;

    /** A possible component in the "allow" bit flag field. */
    public static final int ALLOW_JUNIOR = 0x0004;

    /** A possible component in the "allow" bit flag field. */
    public static final int ALLOW_SENIOR = 0x0008;

    /** A possible component in the "allow" bit flag field. */
    public static final int ALLOW_SENIOR_5_YEAR = 0x0010;

    /** A possible component in the "allow" bit flag field. */
    public static final int ALLOW_SENIOR_POST_BACC = 0x0020;

    /** A possible component in the "allow" bit flag field. */
    public static final int ALLOW_SENIOR_SECOND_BACC = 0x0040;

    /** A possible component in the "allow" bit flag field. */
    public static final int ALLOW_UNDERGRADUATE = 0x007F;

    /** A possible component in the "allow" bit flag field. */
    public static final int ALLOW_GRADUATE = 0x0100;

    /** A possible component in the "allow" bit flag field. */
    public static final int ALLOW_PROFESSIONAL = 0x0200;

    /** A possible component in the "allow" bit flag field. */
    public static final int ALLOW_SELF_IMPROVEMENT = 0x0400;

    /** A field name for serialization of records. */
    private static final String FLD_COURSE_NUMBER = "course_number";

    /** A field name for serialization of records. */
    private static final String FLD_TITLE = "title";

    /** A field name for serialization of records. */
    private static final String FLD_DESCRIPTION = "description";

    /** A field name for serialization of records. */
    private static final String FLD_REGISTRATION_INFO = "registration_info";

    /** A field name for serialization of records. */
    private static final String FLD_RESTRICTION = "restriction";

    /** A field name for serialization of records. */
    private static final String FLD_TERMS_OFFERED = "terms_offered";

    /** A field name for serialization of records. */
    private static final String FLD_GRADE_MODE = "grade_mode";

    /** A field name for serialization of records. */
    private static final String FLD_SPECIAL_COURSE_FEE = "special_course_fee";

    /** A field name for serialization of records. */
    private static final String FLD_ADDITIONAL_INFO = "additional_info";

    /** A field name for serialization of records. */
    private static final String FLD_GT_CODE = "gt_code";

    /** A field name for serialization of records. */
    private static final String FLD_MIN_CREDITS = "min_credits";

    /** A field name for serialization of records. */
    private static final String FLD_MAX_CREDITS = "max_credits";

    /**
     * The course number field value, such as "MATH 126".  This represents the course_id, prefix, and number fields,
     * which must be set together as a unit.
     */
    public CatalogCourseNumber courseNumber;

    /** The 'title' field value, such as "Topology". */
    public String title;

    /** The 'description' field value, with the catalog course description. */
    public String description;

    /** The 'prerequisite' field value. */
    public String prerequisite;

    /** The 'registration_info' field value from the catalog. */
    public String registrationInfo;

    /** The 'restriction' field value from the catalog. */
    public String restriction;

    /** The 'terms_offered' field value, with the terms in which the course is offered. */
    private EnumSet<EOfferingTermName> termsOffered;

    /** The 'grade_mode' field value from the catalog. */
    private EGradeMode gradeMode;

    /** The 'special_course_fee' field value from the catalog. */
    public String specialCourseFee;

    /** The 'additional_info' field value from the catalog. */
    public String additionalInfo;

    /** The 'gt_code' field value from the catalog, such as "MA1". */
    private String gtCode;

    /** The minimum (or fixed) number of credits. */
    private Integer minCredits;

    /** The maximum (or fixed) number of credits. */
    private Integer maxCredits;

    /**
     * Constructs a new {@code CatalogCourseRec}.
     */
    public CatalogCourseRec() {

        super();
    }

    /**
     * Constructs a new {@code CatalogCourseRec} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static CatalogCourseRec parse(final String toParse) {

        final CatalogCourseRec result = new CatalogCourseRec();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets the terms during which the catalog says the course is offered.
     *
     * @param offeringString the string representation from the catalog, such as "Fall, Spring."
     */
    public void setTermsOffered(final String offeringString) {

        final EnumSet<EOfferingTermName> set = EnumSet.noneOf(EOfferingTermName.class);

        final String[] list = offeringString.split(CoreConstants.COMMA);
        for (final String item : list) {
            final String trimmed = item.trim().replace(".", "").toLowerCase(Locale.ROOT);

            if (trimmed.startsWith("fall")) {
                if ("fall".equals(trimmed)) {
                    set.add(EOfferingTermName.EVERY_FALL);
                } else if ("fall (even years)".equals(trimmed)) {
                    set.add(EOfferingTermName.FALL_EVEN_YEARS);
                } else if ("fall (odd years)".equals(trimmed)) {
                    set.add(EOfferingTermName.FALL_ODD_YEARS);
                } else if ("fall (every third year)".equals(trimmed)) {
                    set.add(EOfferingTermName.FALL_THIRD_YEARS);
                } else if ("fall (as needed)".equals(trimmed) || "fall offered as needed".equals(trimmed)) {
                    set.add(EOfferingTermName.FALL_AS_NEEDED);
                } else if ("fall spring".equals(trimmed)) {
                    set.add(EOfferingTermName.EVERY_FALL);
                    set.add(EOfferingTermName.EVERY_SPRING);
                } else {
                    throw new IllegalArgumentException("Invalid term name in list: '" + trimmed + "'");
                }
            } else if (trimmed.startsWith("spring")) {
                if (trimmed.equals("spring")) {
                    set.add(EOfferingTermName.EVERY_SPRING);
                } else if ("spring (even years)".equals(trimmed)) {
                    set.add(EOfferingTermName.SPRING_EVEN_YEARS);
                } else if ("spring (odd years)".equals(trimmed)) {
                    set.add(EOfferingTermName.SPRING_ODD_YEARS);
                } else if ("spring (every third year)".equals(trimmed)) {
                    set.add(EOfferingTermName.SPRING_THIRD_YEARS);
                } else if ("spring (as needed)".equals(trimmed) || "spring offered as needed".equals(trimmed)) {
                    set.add(EOfferingTermName.SPRING_AS_NEEDED);
                } else {
                    throw new IllegalArgumentException("Invalid term name in list: '" + trimmed + "'");
                }
            } else if (trimmed.startsWith("summer")) {
                if (trimmed.equals("summer")) {
                    set.add(EOfferingTermName.EVERY_SUMMER);
                } else if ("summer (even years)".equals(trimmed)) {
                    set.add(EOfferingTermName.SUMMER_EVEN_YEARS);
                } else if ("summer (odd years)".equals(trimmed)) {
                    set.add(EOfferingTermName.SUMMER_ODD_YEARS);
                } else if ("summer (every third year)".equals(trimmed)) {
                    set.add(EOfferingTermName.SUMMER_THIRD_YEARS);
                } else if ("summer (as needed)".equals(trimmed) || "summer offered as needed".equals(trimmed)) {
                    set.add(EOfferingTermName.SUMMER_AS_NEEDED);
                } else {
                    throw new IllegalArgumentException("Invalid term name in list: '" + trimmed + "'");
                }
            } else {
                throw new IllegalArgumentException("Invalid term name in list: '" + trimmed + "'");
            }
        }

        this.termsOffered = set;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown If a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_COURSE_NUMBER.equals(name)) {
            this.courseNumber = CatalogCourseNumber.parse(value);
        } else if (FLD_TITLE.equals(name)) {
            this.title = value;
        } else if (FLD_DESCRIPTION.equals(name)) {
            this.description = value;
        } else if (FLD_REGISTRATION_INFO.equals(name)) {
            this.registrationInfo = value;
        } else if (FLD_RESTRICTION.equals(name)) {
            this.restriction = value;
        } else if (FLD_TERMS_OFFERED.equals(name)) {
            setTermsOffered(value);
        } else if (FLD_GRADE_MODE.equals(name)) {
            final int intCode = Integer.parseInt(value);
            this.gradeMode = EGradeMode.forCode(intCode);
        } else if (FLD_SPECIAL_COURSE_FEE.equals(name)) {
            this.specialCourseFee = value;
        } else if (FLD_ADDITIONAL_INFO.equals(name)) {
            this.additionalInfo = value;
        } else if (FLD_GT_CODE.equals(name)) {
            this.gtCode = value;
        } else if (FLD_MIN_CREDITS.equals(name)) {
            this.minCredits = Integer.valueOf(value);
        } else if (FLD_MAX_CREDITS.equals(name)) {
            this.maxCredits = Integer.valueOf(value);
        }
    }

    /**
     * Constructs a new {@code CatalogCourseRec}.
     *
     * @param theCourseNumber     the course number, such as "MATH 126"
     * @param theTitle            the course title, such as "Numerical Trigonometry"
     * @param theDescription      the catalog description
     * @param theRegistrationInfo the registration information listed in the catalog
     * @param theRestriction      the restriction listed in the catalog
     * @param theTermsOffered     the terms in which the course is offered
     * @param theGradeMode        the grade mode specified in the catalog
     * @param theSpecialCourseFee the special course fee field from the catalog
     * @param theAdditionalInfo   the additional information field from the catalog
     * @param theGtCode           the GTPathways code, such as "MA1"
     * @param theMinCredits       the minimum (or fixed) number of credits
     * @param theMaxCredits       the maximum (or fixed) number of credits
     */
    public CatalogCourseRec(final CatalogCourseNumber theCourseNumber, final String theTitle,
                            final String theDescription, final String theRegistrationInfo, final String theRestriction,
                            final EnumSet<EOfferingTermName> theTermsOffered, final EGradeMode theGradeMode,
                            final String theSpecialCourseFee, final String theAdditionalInfo,
                            final String theGtCode, final Integer theMinCredits, final Integer theMaxCredits) {

        super();

        this.courseNumber = theCourseNumber;
        this.title = theTitle;
        this.description = theDescription;
        this.registrationInfo = theRegistrationInfo;
        this.restriction = theRestriction;
        this.termsOffered = theTermsOffered == null ? null : EnumSet.copyOf(theTermsOffered);
        this.gradeMode = theGradeMode;
        this.specialCourseFee = theSpecialCourseFee;
        this.additionalInfo = theAdditionalInfo;
        this.gtCode = theGtCode;
        this.minCredits = theMinCredits;
        this.maxCredits = theMaxCredits;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final CatalogCourseRec o) {

        return compareAllowingNull(this.courseNumber, o.courseNumber);
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_COURSE_NUMBER, this.courseNumber);
        htm.add(DIVIDER);
        appendField(htm, FLD_TITLE, this.title);
        htm.add(DIVIDER);
        appendField(htm, FLD_DESCRIPTION, this.description);
        htm.add(DIVIDER);
        appendField(htm, FLD_REGISTRATION_INFO, this.registrationInfo);
        htm.add(DIVIDER);
        appendField(htm, FLD_RESTRICTION, this.restriction);
        htm.add(DIVIDER);
        if (this.termsOffered == null) {
            appendField(htm, FLD_TERMS_OFFERED, null);
        } else {
            htm.add(FLD_TERMS_OFFERED, "=");
            boolean comma = false;
            for (final EOfferingTermName offerTerm : this.termsOffered) {
                if (comma) {
                    htm.add(',');
                }
                htm.add(offerTerm.label);
                comma = true;
            }
        }
        htm.add(DIVIDER);
        appendField(htm, FLD_GRADE_MODE, this.gradeMode);
        htm.add(DIVIDER);
        appendField(htm, FLD_SPECIAL_COURSE_FEE, this.specialCourseFee);
        htm.add(DIVIDER);
        appendField(htm, FLD_ADDITIONAL_INFO, this.additionalInfo);
        htm.add(DIVIDER);
        appendField(htm, FLD_GT_CODE, this.gtCode);
        htm.add(DIVIDER);
        appendField(htm, FLD_MIN_CREDITS, this.minCredits);
        htm.add(DIVIDER);
        appendField(htm, FLD_MAX_CREDITS, this.maxCredits);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return Objects.hashCode(this.courseNumber)
                + Objects.hashCode(this.title)
                + Objects.hashCode(this.description)
                + Objects.hashCode(this.registrationInfo)
                + Objects.hashCode(this.restriction)
                + Objects.hashCode(this.termsOffered)
                + Objects.hashCode(this.gradeMode)
                + Objects.hashCode(this.specialCourseFee)
                + Objects.hashCode(this.additionalInfo)
                + Objects.hashCode(this.gtCode)
                + Objects.hashCode(this.minCredits)
                + Objects.hashCode(this.maxCredits);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final CatalogCourseRec rec) {
            equal = Objects.equals(this.courseNumber, rec.courseNumber)
                    && Objects.equals(this.title, rec.title)
                    && Objects.equals(this.description, rec.description)
                    && Objects.equals(this.registrationInfo, rec.registrationInfo)
                    && Objects.equals(this.restriction, rec.restriction)
                    && Objects.equals(this.termsOffered, rec.termsOffered)
                    && Objects.equals(this.gradeMode, rec.gradeMode)
                    && Objects.equals(this.specialCourseFee, rec.specialCourseFee)
                    && Objects.equals(this.additionalInfo, rec.additionalInfo)
                    && Objects.equals(this.gtCode, rec.gtCode)
                    && Objects.equals(this.minCredits, rec.minCredits)
                    && Objects.equals(this.maxCredits, rec.maxCredits);
        } else {
            equal = false;
        }

        return equal;
    }
}
