package dev.mathops.db.old.rec;

import dev.mathops.core.EqualityTests;
import dev.mathops.core.builder.HtmlBuilder;

import java.util.Objects;

/**
 * A "mastery attempt QA" record.
 */
public final class MasteryAttemptQaRec extends RecBase implements Comparable<MasteryAttemptQaRec> {

    /** A field name for serialization of records. */
    private static final String FLD_SERIAL_NBR = "serial_nbr";

    /** A field name for serialization of records. */
    private static final String FLD_EXAM_ID = "exam_id";

    /** A field name for serialization of records. */
    private static final String FLD_QUESTION_NBR = "question_nbr";

    /** A field name for serialization of records. */
    private static final String FLD_CORRECT = "correct";

    /** The 'serial_nbr' field value. */
    public Integer serialNbr;

    /** The 'exam_id' field value. */
    public String examId;

    /** The 'question_nbr' field value. */
    public Integer questionNbr;

    /** The 'correct' field value. */
    public String correct;

    /**
     * Constructs a new {@code MasteryAttemptQaRec}.
     */
    public MasteryAttemptQaRec() {

        super();
    }

    /**
     * Constructs a new {@code MasteryAttemptQaRec} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static MasteryAttemptQaRec parse(final String toParse) {

        final MasteryAttemptQaRec result = new MasteryAttemptQaRec();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown if a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_SERIAL_NBR.equals(name)) {
            this.serialNbr = Integer.valueOf(value);
        } else if (FLD_EXAM_ID.equals(name)) {
            this.examId = value;
        } else if (FLD_QUESTION_NBR.equals(name)) {
            this.questionNbr = Integer.valueOf(value);
        } else if (FLD_CORRECT.equals(name)) {
            this.correct = value;
        }
    }

    /**
     * Constructs a new {@code MasteryAttemptQaRec}.
     *
     * @param theSerialNbr   the serial number
     * @param theExamId      the exam ID
     * @param theQuestionNbr the question number
     * @param theCorrect     "Y" if correct, "N" if not
     */
    public MasteryAttemptQaRec(final Integer theSerialNbr, final String theExamId,
                               final Integer theQuestionNbr, final String theCorrect) {

        super();

        this.serialNbr = theSerialNbr;
        this.examId = theExamId;
        this.questionNbr = theQuestionNbr;
        this.correct = theCorrect;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final MasteryAttemptQaRec o) {

        int result = compareAllowingNull(this.serialNbr, o.serialNbr);

        if (result == 0) {
            result = compareAllowingNull(this.examId, o.examId);

            if (result == 0) {
                result = compareAllowingNull(this.questionNbr, o.questionNbr);
            }
        }

        return result;
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_SERIAL_NBR, this.serialNbr);
        htm.add(DIVIDER);
        appendField(htm, FLD_EXAM_ID, this.examId);
        htm.add(DIVIDER);
        appendField(htm, FLD_QUESTION_NBR, this.questionNbr);
        htm.add(DIVIDER);
        appendField(htm, FLD_CORRECT, this.correct);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return Objects.hashCode(this.serialNbr) //
                + Objects.hashCode(this.examId) //
                + Objects.hashCode(this.questionNbr) //
                + Objects.hashCode(this.correct); //
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final MasteryAttemptQaRec rec) {
            equal = Objects.equals(this.serialNbr, rec.serialNbr)
                    && Objects.equals(this.examId, rec.examId)
                    && Objects.equals(this.questionNbr, rec.questionNbr)
                    && Objects.equals(this.correct, rec.correct);
        } else {
            equal = false;
        }

        return equal;
    }
}
