package jwabbit.gui;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.Serial;

/**
 * An "about" dialog.
 */
final class AboutDialog extends JDialog implements ActionListener {

    /** Version number for serialization. */
    @Serial
    private static final long serialVersionUID = -4706554524817135868L;

    /**
     * Constructs a new {@code AboutDialog}.
     *
     * @param owner the owning frame
     */
    AboutDialog(final JFrame owner) {

        super(owner);

        setTitle("About");
        final JPanel content = new JPanel(new BorderLayout(15, 15));
        content.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        setContentPane(content);

        final JPanel north = new JPanel(new BorderLayout(20, 20));
        content.add(north, BorderLayout.PAGE_START);

        final BufferedImage icon = Gui.loadImage("wabbitemu_32.png");
        final JLabel iconLbl = new JLabel(new ImageIcon(icon));
        north.add(iconLbl, BorderLayout.LINE_START);

        final JPanel grid1 = new JPanel(new GridLayout(3, 1, 6, 6));
        grid1.add(new JLabel("JWabbitemu"));
        grid1.add(new JLabel("0.1 Alpha"));
        grid1.add(new JLabel("Steve Benoit"));
        north.add(grid1, BorderLayout.CENTER);

        final JPanel center = new JPanel(new GridLayout(3, 1, 2, 2));
        center.add(new JLabel("Based on Wabbitemu, 1.8.2.26, Revolution Software"));
        center.add(new JLabel("BootFree \u00a9 2006-2007 Ben Moody"));
        center.add(new JLabel("Rom8x \u00a9 2006-2007 Andree Chea"));
        content.add(center, BorderLayout.CENTER);

        final JPanel flow = new JPanel(new FlowLayout(FlowLayout.CENTER));
        final JButton btn = new JButton("OK");
        btn.addActionListener(this);
        flow.add(btn);
        content.add(flow, BorderLayout.PAGE_END);

        pack();

        final Rectangle ownerBounds = owner.getBounds();
        final Dimension size = getSize();
        setLocation(ownerBounds.x + (ownerBounds.width - size.width) / 2,
                ownerBounds.y + (ownerBounds.height - size.height) / 2);

        setVisible(true);
    }

    /**
     * Handles actions generated by the "OK" button.
     *
     * @param e the action event
     */
    @Override
    public void actionPerformed(final ActionEvent e) {

        setVisible(false);
        dispose();
    }
}
