package dev.mathops.db.old.rawrecord;

import dev.mathops.commons.builder.HtmlBuilder;
import dev.mathops.db.old.rec.RecBase;

import java.util.Objects;

/**
 * A raw "item" record.
 */
public final class RawItem extends RecBase implements Comparable<RawItem> {

    /** A field name. */
    private static final String FLD_ITEM_ID = "item_id";

    /** The item ID. */
    public String itemId;

    /**
     * Constructs a new {@code RawItem}.
     */
    private RawItem() {

        super();
    }

    /**
     * Constructs a new {@code RawItem} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static RawItem parse(final String toParse) {

        final RawItem result = new RawItem();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown if a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_ITEM_ID.equals(name)) {
            this.itemId = value;
        }
    }

    /**
     * Constructs a new {@code RawItem}.
     *
     * @param theItemId the item ID
     */
    public RawItem(final String theItemId) {

        super();

        this.itemId = theItemId;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final RawItem o) {

        return compareAllowingNull(this.itemId, o.itemId);
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_ITEM_ID, this.itemId);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return Objects.hashCode(this.itemId);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final RawItem rec) {
            equal = Objects.equals(this.itemId, rec.itemId);
        } else {
            equal = false;
        }

        return equal;
    }
}
