package dev.mathops.db.old.rawrecord;

import dev.mathops.commons.EqualityTests;
import dev.mathops.commons.builder.HtmlBuilder;
import dev.mathops.db.old.rec.RecBase;

import java.util.Objects;

/**
 * An immutable record of a lesson.
 */
public final class RawLesson extends RecBase implements Comparable<RawLesson> {

    /** A field name. */
    private static final String FLD_LESSON_ID = "lesson_id";

    /** A field name. */
    private static final String FLD_LESSON_TYPE = "lesson_type";

    /** A field name. */
    private static final String FLD_DESCR = "descr";

    /** The lesson ID. */
    public String lessonId;

    /** The lesson type ("C" for course, "R" for refresher). */
    public String lessonType;

    /** The description. */
    public String descr;

    /**
     * Constructs a new {@code RawLesson}.
     */
    private RawLesson() {

        super();
    }

    /**
     * Constructs a new {@code RawLesson} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static RawLesson parse(final String toParse) {

        final RawLesson result = new RawLesson();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown if a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_LESSON_ID.equals(name)) {
            this.lessonId = value;
        } else if (FLD_LESSON_TYPE.equals(name)) {
            this.lessonType = value;
        } else if (FLD_DESCR.equals(name)) {
            this.descr = value;
        }
    }

    /**
     * Constructs a new {@code RawLesson}.
     *
     * @param theLessonId    the lesson ID
     * @param theLessonType  the lesson type
     * @param theDescription the description
     */
    public RawLesson(final String theLessonId, final String theLessonType,
                     final String theDescription) {

        super();

        this.lessonId = theLessonId;
        this.lessonType = theLessonType;
        this.descr = theDescription;
    }

    /**
     * Generates the string representation of the object.
     *
     * @return the string representation
     */
    @Override
    public String toString() {

        return this.descr == null ? this.lessonId : this.descr;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final RawLesson o) {

        return this.lessonId.compareTo(o.lessonId);
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_LESSON_ID, this.lessonId);
        htm.add(DIVIDER);
        appendField(htm, FLD_LESSON_TYPE, this.lessonType);
        htm.add(DIVIDER);
        appendField(htm, FLD_DESCR, this.descr);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return Objects.hashCode(this.lessonId)
                + Objects.hashCode(this.lessonType)
                + Objects.hashCode(this.descr);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final RawLesson rec) {
            equal = Objects.equals(this.lessonId, rec.lessonId)
                    && Objects.equals(this.lessonType, rec.lessonType)
                    && Objects.equals(this.descr, rec.descr);
        } else {
            equal = false;
        }

        return equal;
    }
}
