package dev.mathops.db.old.rawrecord;

import dev.mathops.commons.builder.HtmlBuilder;
import dev.mathops.db.type.TermKey;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Objects;

/**
 * A raw "pacing_rules" record.
 */
public final class RawPacingRules extends RawTermRecordBase implements Comparable<RawPacingRules> {

    /** A field name. */
    private static final String FLD_PACING_STRUCTURE = "pacing_structure";

    /** A field name. */
    private static final String FLD_ACTIVITY_TYPE = "activity_type";

    /** A field name. */
    private static final String FLD_REQUIREMENT = "requirement";

    /** The 'pacing_structure' field value. */
    public String pacingStructure;

    /** The 'activity_type' field value. */
    public String activityType;

    /** The 'requirement' field value. */
    public String requirement;

    /**
     * Constructs a new {@code RawPacingRules}.
     */
    private RawPacingRules() {

        super();
    }

    /**
     * Constructs a new {@code RawPacingRules} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static RawPacingRules parse(final String toParse) {

        final RawPacingRules result = new RawPacingRules();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown if a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_TERM.equals(name)) {
            this.termKey = TermKey.parseLongString(value);
        } else if (FLD_PACING_STRUCTURE.equals(name)) {
            this.pacingStructure = value;
        } else if (FLD_ACTIVITY_TYPE.equals(name)) {
            this.activityType = value;
        } else if (FLD_REQUIREMENT.equals(name)) {
            this.requirement = value;
        }
    }

    /**
     * Constructs a new {@code RawPacingRules}.
     *
     * @param theTermKey         the term key
     * @param thePacingStructure the pacing structure ID
     * @param theActivityType    the activity type
     * @param theRequirement     the requirement
     */
    public RawPacingRules(final TermKey theTermKey, final String thePacingStructure,
                          final String theActivityType, final String theRequirement) {

        super(theTermKey);

        this.pacingStructure = thePacingStructure;
        this.activityType = theActivityType;
        this.requirement = theRequirement;
    }

    /**
     * Extracts a "remote_mpe" record from a result set.
     *
     * @param rs the result set from which to retrieve the record
     * @return the record
     * @throws SQLException if there is an error accessing the database
     */
    public static RawPacingRules fromResultSet(final ResultSet rs) throws SQLException {

        final RawPacingRules result = new RawPacingRules();

        result.termKey = getTermAndYear(rs, FLD_TERM, FLD_TERM_YR);
        result.pacingStructure = getStringField(rs, FLD_PACING_STRUCTURE);
        result.activityType = getStringField(rs, FLD_ACTIVITY_TYPE);
        result.requirement = getStringField(rs, FLD_REQUIREMENT);

        return result;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared.
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object.
     */
    @Override
    public int compareTo(final RawPacingRules o) {

        int result = this.termKey.compareTo(o.termKey);

        if (result == 0) {
            result = this.pacingStructure.compareTo(o.pacingStructure);
            if (result == 0) {
                result = this.activityType.compareTo(o.activityType);
                if (result == 0) {
                    result = this.requirement.compareTo(o.requirement);
                }
            }
        }

        return result;
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_TERM, this.termKey);
        htm.add(DIVIDER);
        appendField(htm, FLD_PACING_STRUCTURE, this.pacingStructure);
        htm.add(DIVIDER);
        appendField(htm, FLD_ACTIVITY_TYPE, this.activityType);
        htm.add(DIVIDER);
        appendField(htm, FLD_REQUIREMENT, this.requirement);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return Objects.hashCode(this.termKey)
                + Objects.hashCode(this.pacingStructure)
                + Objects.hashCode(this.activityType)
                + Objects.hashCode(this.requirement);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final RawPacingRules rec) {
            equal = Objects.equals(this.termKey, rec.termKey)
                    && Objects.equals(this.pacingStructure, rec.pacingStructure)
                    && Objects.equals(this.activityType, rec.activityType)
                    && Objects.equals(this.requirement, rec.requirement);
        } else {
            equal = false;
        }

        return equal;
    }
}
