package dev.mathops.db.old.rawrecord;

import dev.mathops.core.EqualityTests;
import dev.mathops.core.builder.HtmlBuilder;
import dev.mathops.db.old.rec.RecBase;

import java.util.Objects;

/**
 * A raw "std" record. The primary key is std_id.
 */
public final class RawStd extends RecBase implements Comparable<RawStd> {

    /** A field name. */
    private static final String FLD_STD_ID = "std_id";

    /** A field name. */
    private static final String FLD_MASTERY_GROUPS = "mastery_groups";

    /** The 'std_id' field value. The unique ID of the standard. */
    public String stdId;

    /**
     * The 'mastery_groups' field value. An OR of bit flags, one for each item group that must be mastered to have
     * mastered the standard. Typically, 0x01, 0x03, or 0x07, if there are 1, 2, or 3 item groups needed, respectively.
     */
    public Integer masteryGroups;

    /**
     * Constructs a new {@code RawStd}.
     */
    private RawStd() {

        super();
    }

    /**
     * Constructs a new {@code RawStd} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static RawStd parse(final String toParse) {

        final RawStd result = new RawStd();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown if a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_STD_ID.equals(name)) {
            this.stdId = value;
        } else if (FLD_MASTERY_GROUPS.equals(name)) {
            this.masteryGroups = Integer.valueOf(value);
        }
    }

    /**
     * Constructs a new {@code RawStd}.
     *
     * @param theStdId         the standard ID
     * @param theMasteryGroups bit flags indicating the item groups the student must master to master the standard
     */
    public RawStd(final String theStdId, final Integer theMasteryGroups) {

        super();

        this.stdId = theStdId;
        this.masteryGroups = theMasteryGroups;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final RawStd o) {

        return this.stdId.compareTo(o.stdId);
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_STD_ID, this.stdId);
        htm.add(DIVIDER);
        appendField(htm, FLD_MASTERY_GROUPS, this.masteryGroups);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return EqualityTests.objectHashCode(this.stdId)
                + EqualityTests.objectHashCode(this.masteryGroups);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final RawStd rec) {
            equal = Objects.equals(this.stdId, rec.stdId)
                    && Objects.equals(this.masteryGroups, rec.masteryGroups);
        } else {
            equal = false;
        }

        return equal;
    }
}
