package dev.mathops.db.old.rawrecord;

import dev.mathops.core.EqualityTests;
import dev.mathops.core.builder.HtmlBuilder;
import dev.mathops.db.old.rec.RecBase;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Objects;

/**
 * A raw "stmsg" record.
 */
public final class RawStmsg extends RecBase implements Comparable<RawStmsg> {

    /** A field name. */
    private static final String FLD_STU_ID = "stu_id";

    /** A field name. */
    private static final String FLD_MSG_DT = "msg_dt";

    /** A field name. */
    private static final String FLD_PACE = "pace";

    /** A field name. */
    private static final String FLD_COURSE_INDEX = "course_index";

    /** A field name. */
    private static final String FLD_TOUCH_POINT = "touch_point";

    /** A field name. */
    private static final String FLD_MSG_CODE = "msg_code";

    /** A field name. */
    private static final String FLD_SENDER = "sender";

    /** The 'stu_id' field value. */
    public String stuId;

    /** The 'msg_dt' field value. */
    public LocalDate msgDt;

    /** The student's pace at the time the message was sent. */
    public Integer pace;

    /** The index (1-pace) of the course to which the message applies, 0 for pre-course. */
    public Integer courseIndex;

    /** The 'touch_point' field value. */
    public String touchPoint;

    /** The 'msg_code' field value. */
    public String msgCode;

    /** The 'sender' field value. */
    public String sender;

    /**
     * Constructs a new {@code RawStmsg}.
     */
    private RawStmsg() {

        super();
    }

    /**
     * Constructs a new {@code RawStmsg} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static RawStmsg parse(final String toParse) {

        final RawStmsg result = new RawStmsg();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown if a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_STU_ID.equals(name)) {
            this.stuId = value;
        } else if (FLD_MSG_DT.equals(name)) {
            this.msgDt = LocalDate.parse(value);
        } else if (FLD_PACE.equals(name)) {
            this.pace = Integer.valueOf(value);
        } else if (FLD_COURSE_INDEX.equals(name)) {
            this.courseIndex = Integer.valueOf(value);
        } else if (FLD_TOUCH_POINT.equals(name)) {
            this.touchPoint = value;
        } else if (FLD_MSG_CODE.equals(name)) {
            this.msgCode = value;
        } else if (FLD_SENDER.equals(name)) {
            this.sender = value;
        }
    }

    /**
     * Constructs a new {@code RawStmsg}.
     *
     * @param theStuId       the student ID
     * @param theMsgDt       the message date
     * @param thePace        the student's pace at the time the message was sent
     * @param theCourseIndex the index (1-pace) of the course to which the message applies, 0 for pre-course
     * @param theTouchPoint  the touch point
     * @param theMsgCode     the message code
     * @param theSender      the sender
     */
    public RawStmsg(final String theStuId, final LocalDate theMsgDt, final Integer thePace,
                    final Integer theCourseIndex, final String theTouchPoint, final String theMsgCode,
                    final String theSender) {

        super();

        this.stuId = theStuId;
        this.msgDt = theMsgDt;
        this.pace = thePace;
        this.courseIndex = theCourseIndex;
        this.touchPoint = theTouchPoint;
        this.msgCode = theMsgCode;
        this.sender = theSender;
    }

    /**
     * Extracts a "stmsg" record from a result set.
     *
     * @param rs the result set from which to retrieve the record
     * @return the record
     * @throws SQLException if there is an error accessing the database
     */
    public static RawStmsg fromResultSet(final ResultSet rs) throws SQLException {

        final RawStmsg result = new RawStmsg();

        result.stuId = getStringField(rs, FLD_STU_ID);
        result.msgDt = getDateField(rs, FLD_MSG_DT);
        result.pace = getIntegerField(rs, FLD_PACE);
        result.courseIndex = getIntegerField(rs, FLD_COURSE_INDEX);
        result.touchPoint = getStringField(rs, FLD_TOUCH_POINT);
        result.msgCode = getStringField(rs, FLD_MSG_CODE);
        result.sender = getStringField(rs, FLD_SENDER);

        return result;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final RawStmsg o) {

        int result = compareAllowingNull(this.stuId, o.stuId);

        if (result == 0) {
            result = compareAllowingNull(this.msgDt, o.msgDt);
            if (result == 0) {
                result = compareAllowingNull(this.msgCode, o.msgCode);
            }
        }

        return result;
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_STU_ID, this.stuId);
        htm.add(DIVIDER);
        appendField(htm, FLD_MSG_DT, this.msgDt);
        htm.add(DIVIDER);
        appendField(htm, FLD_PACE, this.pace);
        htm.add(DIVIDER);
        appendField(htm, FLD_COURSE_INDEX, this.courseIndex);
        htm.add(DIVIDER);
        appendField(htm, FLD_TOUCH_POINT, this.touchPoint);
        htm.add(DIVIDER);
        appendField(htm, FLD_MSG_CODE, this.msgCode);
        htm.add(DIVIDER);
        appendField(htm, FLD_SENDER, this.sender);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return EqualityTests.objectHashCode(this.stuId)
                + EqualityTests.objectHashCode(this.msgDt)
                + EqualityTests.objectHashCode(this.pace)
                + EqualityTests.objectHashCode(this.courseIndex)
                + EqualityTests.objectHashCode(this.touchPoint)
                + EqualityTests.objectHashCode(this.msgCode)
                + EqualityTests.objectHashCode(this.sender);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final RawStmsg rec) {
            equal = Objects.equals(this.stuId, rec.stuId)
                    && Objects.equals(this.msgDt, rec.msgDt)
                    && Objects.equals(this.pace, rec.pace)
                    && Objects.equals(this.courseIndex, rec.courseIndex)
                    && Objects.equals(this.touchPoint, rec.touchPoint)
                    && Objects.equals(this.msgCode, rec.msgCode)
                    && Objects.equals(this.sender, rec.sender);
        } else {
            equal = false;
        }

        return equal;
    }
}
