package dev.mathops.db.rec;

import dev.mathops.core.EqualityTests;
import dev.mathops.core.builder.HtmlBuilder;

import java.util.Objects;

/**
 * A "report permissions" record.
 */
public final class ReportPermsRec extends RecBase implements Comparable<ReportPermsRec> {

    /** A field name for serialization of records. */
    private static final String FLD_STU_ID = "stu_id";

    /** A field name for serialization of records. */
    private static final String FLD_RPT_ID = "rpt_id";

    /** A field name for serialization of records. */
    private static final String FLD_PERM_LEVEL = "perm_level";

    /** The 'stu_id' field value. */
    public String stuId;

    /** The 'rpt_id' field value. */
    public String rptId;

    /** The 'perm_level' field value. */
    public Integer permLevel;

    /**
     * Constructs a new {@code ReportPermsRec}.
     */
    public ReportPermsRec() {

        super();
    }

    /**
     * Constructs a new {@code ReportPermsRec}.
     *
     * @param theStuId     the student ID
     * @param theRptId     the report ID
     * @param thePermLevel the permission level
     */
    public ReportPermsRec(final String theStuId, final String theRptId, final Integer thePermLevel) {

        super();

        this.stuId = theStuId;
        this.rptId = theRptId;
        this.permLevel = thePermLevel;
    }

    /**
     * Constructs a new {@code ReportPermsRec} by parsing the string format generated by {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static ReportPermsRec parse(final String toParse) {

        final ReportPermsRec result = new ReportPermsRec();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * An {@code IllegalArgumentException} is thrown if a field name is recognized but the value provided cannot be
     * interpreted or if the field name or value string is {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_STU_ID.equals(name)) {
            this.stuId = value;
        } else if (FLD_RPT_ID.equals(name)) {
            this.rptId = value;
        } else if (FLD_PERM_LEVEL.equals(name)) {
            this.permLevel = Integer.valueOf(value);
        }
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final ReportPermsRec o) {

        int result = compareAllowingNull(this.stuId, o.stuId);

        if (result == 0) {
            result = compareAllowingNull(this.rptId, o.rptId);
        }

        return result;
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_STU_ID, this.stuId);
        htm.add(DIVIDER);
        appendField(htm, FLD_RPT_ID, this.rptId);
        htm.add(DIVIDER);
        appendField(htm, FLD_PERM_LEVEL, this.permLevel);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return EqualityTests.objectHashCode(this.stuId) //
                + EqualityTests.objectHashCode(this.rptId) //
                + EqualityTests.objectHashCode(this.permLevel);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final ReportPermsRec rec) {
            equal = Objects.equals(this.stuId, rec.stuId)
                    && Objects.equals(this.rptId, rec.rptId)
                    && Objects.equals(this.permLevel, rec.permLevel);
        } else {
            equal = false;
        }

        return equal;
    }
}
