package dev.mathops.db.rec;

import dev.mathops.core.EqualityTests;
import dev.mathops.core.builder.HtmlBuilder;

import java.util.Objects;

/**
 * A "student unit mastery" record.
 */
public final class StudentUnitMasteryRec extends RecBase implements Comparable<StudentUnitMasteryRec> {

    /** A field name for serialization of records. */
    private static final String FLD_STU_ID = "stu_id";

    /** A field name for serialization of records. */
    private static final String FLD_COURSE_ID = "course_id";

    /** A field name for serialization of records. */
    private static final String FLD_UNIT = "unit";

    /** A field name for serialization of records. */
    private static final String FLD_SCORE = "score";

    /** A field name for serialization of records. */
    private static final String FLD_SR_STATUS = "sr_status";

    /** A field name for serialization of records. */
    private static final String FLD_S1_STATUS = "s1_status";

    /** A field name for serialization of records. */
    private static final String FLD_S2_STATUS = "s2_status";

    /** A field name for serialization of records. */
    private static final String FLD_S3_STATUS = "s3_status";

    /** The 'stu_id' field value. */
    public String stuId;

    /** The 'course_id' field value. */
    public String courseId;

    /** The 'unit' field value. */
    public Integer unit;

    /** The 'score' field value. */
    public Integer score;

    /** The 'sr_status' field value. */
    public String srStatus;

    /** The 's1_status' field value. */
    public String s1Status;

    /** The 's2_status' field value. */
    public String s2Status;

    /** The 's3_status' field value. */
    public String s3Status;

    /**
     * Constructs a new {@code StudentUnitMasteryRec}.
     */
    public StudentUnitMasteryRec() {

        super();
    }

    /**
     * Constructs a new {@code StudentUnitMasteryRec} by parsing the string format generated by
     * {@code serializedString}.
     *
     * @param toParse the string to parse
     * @return the parsed object
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    public static StudentUnitMasteryRec parse(final String toParse) {

        final StudentUnitMasteryRec result = new StudentUnitMasteryRec();

        result.parseString(toParse);

        return result;
    }

    /**
     * Sets a field based on its name and the string representation of its value.
     *
     * <p>
     * If the field name is not recognized, no action is taken (perhaps the object is being deserialized from an old
     * record created at a time when a field was present that has since been removed).
     *
     * <p>
     * If a field name is recognized, however, and the value provided cannot be interpreted, an
     * {@code IllegalArgumentException} is thrown. Such an exception is also thrown if the field name or value string is
     * {@code null}.
     *
     * @param name  the field name
     * @param value the value
     * @throws IllegalArgumentException if the string cannot be parsed
     */
    @Override
    protected void setField(final String name, final String value) throws IllegalArgumentException {

        if (FLD_STU_ID.equals(name)) {
            this.stuId = value;
        } else if (FLD_COURSE_ID.equals(name)) {
            this.courseId = value;
        } else if (FLD_UNIT.equals(name)) {
            this.unit = Integer.valueOf(value);
        } else if (FLD_SCORE.equals(name)) {
            this.score = Integer.valueOf(value);
        } else if (FLD_SR_STATUS.equals(name)) {
            this.srStatus = value;
        } else if (FLD_S1_STATUS.equals(name)) {
            this.s1Status = value;
        } else if (FLD_S2_STATUS.equals(name)) {
            this.s2Status = value;
        } else if (FLD_S3_STATUS.equals(name)) {
            this.s3Status = value;
        }
    }

    /**
     * Constructs a new {@code StudentUnitMasteryRec}.
     *
     * @param theStuId    the student ID
     * @param theCourseId the course ID
     * @param theUnit     the unit
     * @param theScore    the total score
     * @param theSrStatus the status of the Skills Review
     * @param theS1Status the status of standard 1
     * @param theS2Status the status of standard 2
     * @param theS3Status the status of standard 3
     */
    public StudentUnitMasteryRec(final String theStuId, final String theCourseId,
                                 final Integer theUnit, final Integer theScore, final String theSrStatus,
                                 final String theS1Status, final String theS2Status, final String theS3Status) {

        super();

        this.stuId = theStuId;
        this.courseId = theCourseId;
        this.unit = theUnit;
        this.score = theScore;
        this.srStatus = theSrStatus;
        this.s1Status = theS1Status;
        this.s2Status = theS2Status;
        this.s3Status = theS3Status;
    }

    /**
     * Compares two records for order.
     *
     * @param o the object to be compared
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than
     *         the specified object
     */
    @Override
    public int compareTo(final StudentUnitMasteryRec o) {

        int result = compareAllowingNull(this.stuId, o.stuId);

        if (result == 0) {
            result = compareAllowingNull(this.courseId, o.courseId);

            if (result == 0) {
                result = compareAllowingNull(this.unit, o.unit);
            }
        }

        return result;
    }

    /**
     * Generates a string serialization of the record. Each concrete subclass should have a constructor that accepts a
     * single {@code String} to reconstruct the object from this string.
     *
     * @return the string
     */
    @Override
    public String serializedString() {

        final HtmlBuilder htm = new HtmlBuilder(40);

        appendField(htm, FLD_STU_ID, this.stuId);
        htm.add(DIVIDER);
        appendField(htm, FLD_COURSE_ID, this.courseId);
        htm.add(DIVIDER);
        appendField(htm, FLD_UNIT, this.unit);
        htm.add(DIVIDER);
        appendField(htm, FLD_SCORE, this.score);
        htm.add(DIVIDER);
        appendField(htm, FLD_SR_STATUS, this.srStatus);
        htm.add(DIVIDER);
        appendField(htm, FLD_S1_STATUS, this.s1Status);
        htm.add(DIVIDER);
        appendField(htm, FLD_S2_STATUS, this.s2Status);
        htm.add(DIVIDER);
        appendField(htm, FLD_S3_STATUS, this.s3Status);

        return htm.toString();
    }

    /**
     * Generates a hash code for the object.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {

        return EqualityTests.objectHashCode(this.stuId) //
                + EqualityTests.objectHashCode(this.courseId) //
                + EqualityTests.objectHashCode(this.unit) //
                + EqualityTests.objectHashCode(this.score) //
                + EqualityTests.objectHashCode(this.srStatus) //
                + EqualityTests.objectHashCode(this.s1Status) //
                + EqualityTests.objectHashCode(this.s2Status) //
                + EqualityTests.objectHashCode(this.s3Status);
    }

    /**
     * Tests whether this object is equal to another.
     *
     * @param obj the other object
     * @return true if equal; false if not
     */
    @Override
    public boolean equals(final Object obj) {

        final boolean equal;

        if (obj == this) {
            equal = true;
        } else if (obj instanceof final StudentUnitMasteryRec rec) {
            equal = Objects.equals(this.stuId, rec.stuId)
                    && Objects.equals(this.courseId, rec.courseId)
                    && Objects.equals(this.unit, rec.unit)
                    && Objects.equals(this.score, rec.score)
                    && Objects.equals(this.srStatus, rec.srStatus)
                    && Objects.equals(this.s1Status, rec.s1Status)
                    && Objects.equals(this.s2Status, rec.s2Status)
                    && Objects.equals(this.s3Status, rec.s3Status);
        } else {
            equal = false;
        }

        return equal;
    }
}
