package dev.mathops.app.teststation;

import dev.mathops.core.builder.HtmlBuilder;
import dev.mathops.core.log.Log;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.Serial;

/**
 * A dialog that displays the log in a scrolling window.
 */
class LogViewPanel extends JInternalFrame implements ActionListener {

    /** Version number for serialization. */
    @Serial
    private static final long serialVersionUID = 7710028022845710667L;

    /**
     * Constructs a new {@code LogViewPanel} panel.
     *
     * @param desk the desktop pane that will contain the dialog
     */
    LogViewPanel(final JDesktopPane desk) {

        super("Log Viewer", true, true, true, false);

        final Runnable builder = new LogViewPanelGuiBuilder(desk, this);

        if (SwingUtilities.isEventDispatchThread()) {
            builder.run();
        } else {
            try {
                SwingUtilities.invokeAndWait(builder);
            } catch (final Exception e) { /* Empty */
            }
        }
    }

    /**
     * Handles button presses on the OK button.
     *
     * @param e the action event generated by the button press
     */
    @Override
    public void actionPerformed(final ActionEvent e) {

        if (!SwingUtilities.isEventDispatchThread()) {
            Log.warning(Res.get(Res.NOT_AWT_THREAD));
        }

        setVisible(false);
        dispose();
    }
}

/**
 * A runnable that is to be called in the AWT event dispatcher thread to construct the dialog's GUI.
 */
class LogViewPanelGuiBuilder implements Runnable {

    /** The pane in which to center the dialog. */
    private final JDesktopPane deskPane;

    /** The panel whose GUI is to be built. */
    private final LogViewPanel panel;

    /** The text area. */
    private JTextArea text;

    /**
     * Constructs a new {@code LogViewPanelGuiBuilder}.
     *
     * @param desk     the desktop pane in which to center the dialog
     * @param thePanel the panel whose GUI is to be built
     */
    LogViewPanelGuiBuilder(final JDesktopPane desk, final LogViewPanel thePanel) {

        this.deskPane = desk;
        this.panel = thePanel;
    }

    /**
     * Gets the text area that was generated.
     *
     * @return the text area
     */
    public JTextArea getText() {

        return this.text;
    }

    /**
     * Constructs the user interface.
     */
    @Override
    public void run() {

        if (!SwingUtilities.isEventDispatchThread()) {
            Log.warning(Res.get(Res.NOT_AWT_THREAD));
        }

        final JPanel content = new JPanel(new BorderLayout());

        final Dimension deskSize = this.deskPane.getSize();
        content.setPreferredSize(new Dimension(deskSize.width * 3 / 4, deskSize.height * 3 / 4));
        this.panel.setContentPane(content);

        final JPanel center = new JPanel(new BorderLayout());
        center.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        center.setLayout(new BorderLayout(10, 10));
        content.add(center, BorderLayout.CENTER);

        final int count = Log.getWriter().getNumInList();
        final HtmlBuilder builder = new HtmlBuilder(100 * count);
        for (int i = 0; i < count; ++i) {
            builder.addln(Log.getWriter().getListMessage(i).message);
        }

        // Build the log text area
        this.text = new JTextArea(builder.toString());
        final JScrollPane scroll = new JScrollPane(this.text);
        center.add(scroll, BorderLayout.CENTER);

        // Create the OK button
        final JPanel south = new JPanel(new FlowLayout(FlowLayout.CENTER));
        final JButton btn = new JButton("OK");
        btn.addActionListener(this.panel);
        south.add(btn);
        center.add(south, BorderLayout.SOUTH);

        this.panel.getRootPane().setDefaultButton(btn);

        this.panel.setFocusCycleRoot(true);
        this.panel.pack();

        final Dimension screen = this.deskPane.getSize();
        final Dimension size = this.panel.getSize();
        this.panel.setLocation((screen.width - size.width) / 2, (screen.height - size.height) / 2);
        this.panel.setVisible(true);
        this.panel.requestFocus();
    }
}
